Repository kvp9356/think-jeonju, pull requests merged in 2018-11, with the labels that each got.

#8 Feat/search
  src/main/java/com/kvp/thinkjeonju/controller/ApiSpotController.java
  src/main/java/com/kvp/thinkjeonju/controller/SpotController.java
  src/main/java/com/kvp/thinkjeonju/dto/LikeToDTO.java
  src/main/java/com/kvp/thinkjeonju/dto/SpotDTO.java
  src/main/java/com/kvp/thinkjeonju/exception/spot/CategoryNotFoundException.java
  src/main/java/com/kvp/thinkjeonju/model/Spot.java
  src/main/java/com/kvp/thinkjeonju/repository/SpotMapper.java
  src/main/java/com/kvp/thinkjeonju/service/SpotService.java
  src/main/resources/application.properties
  src/main/resources/mapper/search/spot-mapper.xml
  src/main/resources/static/css/base.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/spotList.css
  src/main/resources/static/image/fullStar.png
  src/main/resources/static/image/jeonjuStation.jpg
  src/main/resources/static/image/search.png
  src/main/resources/static/image/star.png
  src/main/resources/static/js/index.js
  src/main/resources/static/js/spotList.js
  src/main/resources/templates/index.html
  src/main/resources/templates/spotList.html
Labels: SPRINT2

#11 feat: 메인화면 구현
  src/main/java/com/kvp/thinkjeonju/controller/HomeController.java
  src/main/java/com/kvp/thinkjeonju/helper/CustomHelper.java
  src/main/java/com/kvp/thinkjeonju/repository/ScheduleMapper.java
  src/main/java/com/kvp/thinkjeonju/repository/SpotMapper.java
  src/main/java/com/kvp/thinkjeonju/service/ScheduleService.java
  src/main/java/com/kvp/thinkjeonju/service/SpotService.java
  src/main/resources/mapper/schedule/schedule-mapper.xml
  src/main/resources/mapper/spot/spot-mapper.xml
  src/main/resources/static/css/index.css
  src/main/resources/static/css/myPage.css
  src/main/resources/templates/index.html
Labels: SPRINT3

#19 Feat/paging
  src/main/java/com/kvp/thinkjeonju/controller/ApiMyPageController.java
  src/main/java/com/kvp/thinkjeonju/controller/ApiScheduleController.java
  src/main/java/com/kvp/thinkjeonju/controller/ApiSpotController.java
  src/main/java/com/kvp/thinkjeonju/controller/SpotController.java
  src/main/java/com/kvp/thinkjeonju/dto/PageDTO.java
  src/main/java/com/kvp/thinkjeonju/dto/PagingDTO.java
  src/main/java/com/kvp/thinkjeonju/repository/LikeToMapper.java
  src/main/java/com/kvp/thinkjeonju/repository/ScheduleMapper.java
  src/main/java/com/kvp/thinkjeonju/repository/SpotMapper.java
  src/main/java/com/kvp/thinkjeonju/service/MyPageService.java
  src/main/java/com/kvp/thinkjeonju/service/ScheduleService.java
  src/main/java/com/kvp/thinkjeonju/service/SpotService.java
  src/main/java/com/kvp/thinkjeonju/support/Paging.java
  src/main/resources/mapper/likeTo/likeTo-mapper.xml
  src/main/resources/mapper/schedule/schedule-mapper.xml
  src/main/resources/mapper/spot/spot-mapper.xml
  src/main/resources/static/css/myPage.css
  src/main/resources/static/js/index.js
  src/main/resources/static/js/join.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/myPage.js
  src/main/resources/static/js/spotList.js
  src/main/resources/templates/index.html
  src/main/resources/templates/myPage.html
Labels: SPRINT3

#20 Feat/instagram
  src/main/resources/static/css/spotDetail.css
  src/main/resources/static/js/index.js
  src/main/resources/static/js/myPage.js
  src/main/resources/static/js/schedule.js
  src/main/resources/static/js/spotDetail.js
  src/main/resources/static/js/spotList.js
  src/main/resources/templates/base.html
  src/main/resources/templates/spotDetail.html
Labels: SPRINT4

#21 Feat/search
  src/main/java/com/kvp/thinkjeonju/helper/CustomHelper.java
  src/main/resources/static/css/spotDetail.css
  src/main/resources/static/image/instagram.png
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
  src/main/resources/templates/spotDetail.html
Labels: SPRINT4

#22 Feat/schedule
  src/main/java/com/kvp/thinkjeonju/controller/ScheduleController.java
  src/main/java/com/kvp/thinkjeonju/dto/ScheduleDTO.java
  src/main/java/com/kvp/thinkjeonju/helper/CustomHelper.java
  src/main/java/com/kvp/thinkjeonju/model/Schedule.java
  src/main/java/com/kvp/thinkjeonju/repository/LikeToMapper.java
  src/main/java/com/kvp/thinkjeonju/repository/ScheduleMapper.java
  src/main/java/com/kvp/thinkjeonju/service/ScheduleService.java
  src/main/resources/mapper/likeTo/likeTo-mapper.xml
  src/main/resources/mapper/schedule/schedule-mapper.xml
  src/main/resources/static/css/myPage.css
  src/main/resources/static/css/scheduleList.css
  src/main/resources/static/js/scheduleList.js
  src/main/resources/templates/base.html
  src/main/resources/templates/index.html
  src/main/resources/templates/scheduleList.html
Labels: SPRINT4

#24 Feat/search
  src/main/resources/static/css/schedule.css
  src/main/resources/static/css/spotList.css
  src/main/resources/static/image/kvp.jpg
  src/main/resources/static/image/vsh.jpg
  src/main/resources/static/js/schedule.js
  src/main/resources/templates/schedule.html
  src/main/resources/templates/scheduleEdit.html
  src/main/resources/templates/spotList.html
Labels: SPRINT4

#25 Feat/schedule detail connect
  src/main/resources/mapper/schedule/schedule-mapper.xml
  src/main/resources/static/css/myPage.css
  src/main/resources/static/image/writing.png
  src/main/resources/static/js/myPage.js
  src/main/resources/static/js/scheduleList.js
Labels: SPRINT4
